name: pages-auto-deploy

on:
  workflow_dispatch:

concurrency:
  group: pages-auto-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Build
        run: |
          npm ci
          npx @cloudflare/next-on-pages

      - name: Deploy to Cloudflare Pages (retry)
        run: |
          set -euo pipefail
          for attempt in 1 2 3; do
            echo "Deploy attempt $attempt/3"
            if npx wrangler@4.66.0 pages deploy .vercel/output/static --project-name=twincity-ui --branch=main --commit-dirty=true; then
              exit 0
            fi
            if [ "$attempt" -lt 3 ]; then
              sleep 15
            fi
          done
          echo "Cloudflare deploy failed after retries"
          exit 1
